name: todo_with_bloc_pattern
description: ToDo application challange with BLoC pattern

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  bloc: ^8.1.0
  equatable: ^2.0.5
  flutter_easyloading: ^3.0.5
  flutter_spinkit: ^5.1.0
  get_it: ^7.2.0
  shared_preferences: ^2.0.15
  hive_flutter: ^1.1.0
  collection: ^1.16.0
  go_router: ^6.0.6
  json_annotation: ^4.6.0
  meta: ^1.7.0
  uuid: ^3.0.6
  infinite_scroll_pagination: ^3.2.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  json_serializable: ^6.3.1
  hive_generator: ^2.0.0

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
